# Change this variables to reflect your environment

# Your Gx Instance URL
gx_base_url = 'https://pythondemo.dev.int.kneat.cloud/888888-pythonDemo/'

# Your Token Service URL
token_service_url = 'https://pythondemo.dev.int.kneat.cloud/888888-pythonDemo/token'

# Replace with your client ID
client_id = 'ca0e7ca0-97e7-11ed-9b52-afcc857e72d7'

# The redirect URI you registered on the External Application page, this url is generated by this application
callback_uri = 'http://127.0.0.1:5198/callback_oauth'
